version: 0.2
run-as: root
env:
  variables:
    TF_FILES: ""
    TF_VERSION: ""
    name_prefix: ""
    name_suffix: ""
    environment: ""
phases:
    install:
        run-as: root
        runtime-versions:
          python: 3.7
        commands:
            - echo "Entering install phase..."
            - cd /usr/bin
            - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            - unzip terraform_${TF_VERSION}_linux_amd64.zip
            - terraform version
    pre_build:
        commands:
            - echo "Entering build phase..."
    build:
        run-as: root
        commands:
            - echo "Entering build phase..."
            - echo Build started on `date`
            - cd ${CODEBUILD_SRC_DIR}/${TF_FILES}
            - |
              echo "Processing lambda modules ..."; 
              terraform init; 
              terraform plan -var name_prefix=${name_prefix} -var name_suffix=${name_suffix} -var environment=${environment} -out=${environment}_Lambda_final; 
    post_build:
        commands:
           - echo " Completed Terraform Plan phase... "
           - echo plan creation completed on `date`
artifacts:
  files:
    - '**/*'
  name: panong-plan-$(date +%Y-%m-%d)
  discard-paths: no